version: "3"
services:
  server:
    build:
      context: ./
      dockerfile: server-app.Dockerfile
    container_name: gk-server
    volumes:
    - ./:/home/app
    ports:
      - 3000:3000
    command: yarn start

  db:
    build:
      context: ./
      dockerfile: server-db.Dockerfile
    container_name: gk-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
